[package]
name = "rollsum"
version = "0.1.0"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]
repository = "https://github.com/aidanhs/rsroll"
readme = "README.md"
description = "Rolling checksum implementation"
license = "BSD-3-Clause"

[dev-dependencies]
rand = "0.3"
